FROM ghcr.io/verylongdelay/python-uv-base:3-slim

# Install project dependencies
WORKDIR /my-app

# Copy the source code in last to optimize rebuilding the image
COPY . .

RUN uv sync --frozen

ENTRYPOINT ["uv"]
CMD ["run", "python", "-m", "app"]
