name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.10", 3.10-slim, "3.11", 3.11-slim, "3.12", 3.12-slim, "3.13", 3.13-slim, "3", 3-slim]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: ${{ runner.debug && '--debug' || '' }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      # Build and push the container to the GitHub Container
      # Repository. The container will be tagged as "latest"
      # and with the short SHA of the commit.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/verylongdelay/python-uv:${{ matrix.python_version }}
          build-args: |
            python_version=${{ matrix.python_version }}

      - name: Cleanup untagged images
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
            token: ${{ github.token }}
            repository_owner: ${{ github.repository_owner }}
            repository: ${{ github.repository }}
            package_name: ghcr.io/verylongdelay/python-uv
            untagged_only: true
            owner_type: user
            except_untagged_multiplatform: true
